version: '2'
services:
  data:
    container_name: data_container
    build: ./docker/data
    volumes:
      - .:/www
    command: /var/local/entrypoint.sh

  php:
    container_name: php_container
    build: ./docker/php
    volumes_from:
      - data
    environment:
      CACHE_DIR: /www/var/cache
      LOG_DIR: /www/var/logs
      SESSION_DIR: /www/var/sessions
    command: /var/local/entrypoint.sh

  nginx:
    container_name: nginx_container
    build:
      context: ./docker/nginx
    ports:
      - "8001:80"
    links:
      - php
    volumes_from:
      - php
      - data
